### ISSUE TITLE
Trouble running on Windows

### ISSUE THREAD

**Issue by kbtbc** [shikhar1verma/auto-eatventure#3]
I don't have ubuntu desktop, but maybe I try windows native ubuntu environment...  meanwhile, native seems to fail here:

```D:\Temp\auto-eatventure>python adb_autoplay.py
Traceback (most recent call last):
  File "adb_autoplay.py", line 754, in <module>
    dev.init_game()
  File "adb_autoplay.py", line 588, in init_game
    self.capture_screenshot()
  File "adb_autoplay.py", line 105, in capture_screenshot
    pilimg = Image.open(io.BytesIO(output))
  File "C:\Users\Users\AppData\Local\Programs\Python\Python37\lib\site-packages\PIL\Image.py", line 3298, in open
    raise UnidentifiedImageError(msg)
PIL.UnidentifiedImageError: cannot identify image file <_io.BytesIO object at 0x000001F9DD760D68>```

**Comment by shikhar1verma** [comment]
I'll try to run on windows on my brother's laptop. Will try to record the whole thing and share the YouTube link.

**Comment by GenereicUsername** [comment]
I seem to have got it to run with modifying the adb_command so it actually starts the screen capture.
 
adb_command = "C:\\Users\\xxxx\\Desktop\\PTools\\platform-tools\\adb.exe **exec-out screencap -p"**

**Comment by sashaimba13** [comment]
> 



> I seem to have got it to run with modifying the adb_command so it actually starts the screen capture.
> 
> adb_command = "C:\Users\xxxx\Desktop\PTools\platform-tools\adb.exe **exec-out screencap -p"**

you just replaced this in eatventure script or somewhere else?

**Comment by GenereicUsername** [comment]
> > 
> 
> > I seem to have got it to run with modifying the adb_command so it actually starts the screen capture.
> > adb_command = "C:\Users\xxxx\Desktop\PTools\platform-tools\adb.exe **exec-out screencap -p"**
> 
> you just replaced this in eatventure script or somewhere else?

Yes, replaced the adb_command in adb_autoplay.py

**Comment by sashaimba13** [comment]
> > > 
> > 
> > 
> > > I seem to have got it to run with modifying the adb_command so it actually starts the screen capture.
> > > adb_command = "C:\Users\xxxx\Desktop\PTools\platform-tools\adb.exe **exec-out screencap -p"**
> > 
> > 
> > you just replaced this in eatventure script or somewhere else?
> 
> Yes, replaced the adb_command in adb_autoplay.py

what version of python you are using?

**Comment by GenereicUsername** [comment]
> > > > 
> > > 
> > > 
> > > > I seem to have got it to run with modifying the adb_command so it actually starts the screen capture.
> > > > adb_command = "C:\Users\xxxx\Desktop\PTools\platform-tools\adb.exe **exec-out screencap -p"**
> > > 
> > > 
> > > you just replaced this in eatventure script or somewhere else?
> > 
> > 
> > Yes, replaced the adb_command in adb_autoplay.py
> 
> what version of python you are using?

It would be 3.7, i tried to run it on 3.11 but it had some issues.

**Comment by sashaimba13** [comment]
> > > > > 
> > > > 
> > > > 
> > > > > I seem to have got it to run with modifying the adb_command so it actually starts the screen capture.
> > > > > adb_command = "C:\Users\xxxx\Desktop\PTools\platform-tools\adb.exe **exec-out screencap -p"**
> > > > 
> > > > 
> > > > you just replaced this in eatventure script or somewhere else?
> > > 
> > > 
> > > Yes, replaced the adb_command in adb_autoplay.py
> > 
> > 
> > what version of python you are using?
> 
> It would be 3.7, i tried to run it on 3.11 but it had some issues.

(env) C:\py\auto>python adb_autoplay.py
Traceback (most recent call last):
  File "adb_autoplay.py", line 754, in <module>
    dev.init_game()
  File "adb_autoplay.py", line 588, in init_game
    self.capture_screenshot()
  File "adb_autoplay.py", line 102, in capture_screenshot
    output = subprocess.check_output(adb_command.split())
  File "C:\Users\chels\AppData\Local\Programs\Python\Python37\lib\subprocess.py", line 411, in check_output
    **kwargs).stdout
  File "C:\Users\chels\AppData\Local\Programs\Python\Python37\lib\subprocess.py", line 488, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Users\chels\AppData\Local\Programs\Python\Python37\lib\subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "C:\Users\chels\AppData\Local\Programs\Python\Python37\lib\subprocess.py", line 1207, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] Не удается найти указанный файл


now i have this problem :(

**Comment by johanjonsson** [comment]
I am also getting similar error with 

Traceback (most recent call last):
  File "adb_autoplay.py", line 807, in <module>
    dev.init_game()
  File "adb_autoplay.py", line 634, in init_game
    self.capture_screenshot()
  File "adb_autoplay.py", line 102, in capture_screenshot
    output = subprocess.check_output(adb_command.split())
  File "C:\Users\Johan\AppData\Local\Programs\Python\Python37\lib\subprocess.py", line 411, in check_output
    **kwargs).stdout
  File "C:\Users\Johan\AppData\Local\Programs\Python\Python37\lib\subprocess.py", line 488, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Users\Johan\AppData\Local\Programs\Python\Python37\lib\subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "C:\Users\Johan\AppData\Local\Programs\Python\Python37\lib\subprocess.py", line 1207, in _execute_child
    startupinfo)
    
    Didnt work for me to add the exec part here

adb_command = f'adb -s {self.device.serial} shell screencap exec-out screencap -p'

**Comment by zoeywowy** [comment]
I know a way of setting this up if your on windows or mac!

1. Watch one of these videos on how to setup a dual boot os with Ubuntu [**_Watch this If your running Windows OS_**](https://youtu.be/mXyN1aJYefc?si=DXozbTno9lF2u0OU) | [**_Watch this if your running macOS_**](https://youtu.be/KIgxEEzT9ek?si=7Pymn1ybhzGDFSyd)
2. Once installed open the terminal(crtl+alt+T)
3. Now input these commands one after the other to install Python -- `sudo apt update`
`sudo apt install build-essential zlib1g-dev libncurses5-dev libgdbm-dev libnss3-dev libssl-dev libreadline-dev libffi-dev wget`
`sudo mkdir /python && cd /python`
`sudo wget https://www.python.org/ftp/python/3.7.6/Python-3.7.6.tgz`
`sudo tar -xvf Python-3.7.6.tgz`
`cd Python-3.7.6`
`sudo ./configure --enable-optimizations`
`sudo make install`
`python3.7 --version`
4. After that in a new terminal(ctrl+alt+T) input these to install Android Studio -- `sudo apt install openjdk-11-jdk
java --version`
`sudo add-apt-repository ppa:maarten-fonville/android-studio`
`sudo apt update`
`sudo apt install android-studio -y`
5. [**_Now watch this video on how to setup the emulator_**](https://youtu.be/GhuiNcOEv1A?t=91)
6. Next install the ADB files from the terminal you have opened via this command `sudo apt-get install android-sdk-platform-tools`
7. Now input in the same terminal this to install git for cloning the github repository `sudo apt-get install git-all`
8. Download Visual Studio Code from the app center once downloaded click on view then Command Pallet then type in git then click on git clone then paste in this link and hit enter `git clone https://github.com/shikhar1verma/auto-eatventure.git`
9. Then input this into terminal to make the directory for the ENV `sudo mkdir /python-environments && cd /python-environments`
10. Then input in terminal `python3.7 -m venv eatventures-env`
11. Now input in terminal to activate the ENV `source ~/python-environments/eatventures-env/bin/activate`
12. Next in the same terminal input `cd /[the location where repository is]/[next location maybe your name]/auto-eatventure`
13. When the terminal is in the repository directory input this `pip install -r requirements.txt`
14. If you get an Pillow error input this `sudo apt install zlib1g-dev libjpeg-dev` then input `pip install -r requirements.txt` again to finish install
15. Finally but not least [**_download the latest version of Eatventure_**](https://www.google.com/amp/s/apkpure.com/eatventure/com.hwqgrhhjfd.idlefastfood/amp)
16. Open up the emulator you made earlier then drag and drop the apk then let it install once downloaded open it up then login
17. Finally input this to start the automation process `python3.7 adb_autoplay.py`
18. Additionally but highly recommended install MaxAutoClicker from the app center as the bot gets stuck on some gui so once you download it put it on a timer for 15 seconds then click emulate human clicking then set its clicking position on the grass tile or something thats not really in the way and don't worry about the ads since they don't have redirect links hope this helps and enjoy! <3

**Comment by CrystalOrder** [comment]
I'm getting a similar error as [kbtbc](https://github.com/kbtbc) despite using the same versions for everything as original dev.

I tried [sashaimba13](https://github.com/sashaimba13) suggestion of replacing adb_command and making sure adb was pathed correctly but got this error instead.

  File "adb_autoplay.py", line 808, in <module>
    dev.init_game()
  File "adb_autoplay.py", line 635, in init_game
    self.capture_screenshot()
  File "adb_autoplay.py", line 103, in capture_screenshot
    output = subprocess.check_output(adb_command.split())
  File "C:\Users\users\AppData\Local\Programs\Python\Python37\lib\subprocess.py", line 411, in check_output
    **kwargs).stdout
  File "C:\Users\users\AppData\Local\Programs\Python\Python37\lib\subprocess.py", line 488, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Users\users\AppData\Local\Programs\Python\Python37\lib\subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "C:\Users\users\AppData\Local\Programs\Python\Python37\lib\subprocess.py", line 1207, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified

any ideas on how to fix?

**Comment by zoeywowy** [comment]
> I'm getting a similar error as [kbtbc](https://github.com/kbtbc) despite using the same versions for everything as original dev.
> 
> I tried [sashaimba13](https://github.com/sashaimba13) suggestion of replacing adb_command and making sure adb was pathed correctly but got this error instead.
> 
> File "adb_autoplay.py", line 808, in dev.init_game() File "adb_autoplay.py", line 635, in init_game self.capture_screenshot() File "adb_autoplay.py", line 103, in capture_screenshot output = subprocess.check_output(adb_command.split()) File "C:\Users\users\AppData\Local\Programs\Python\Python37\lib\subprocess.py", line 411, in check_output **kwargs).stdout File "C:\Users\users\AppData\Local\Programs\Python\Python37\lib\subprocess.py", line 488, in run with Popen(*popenargs, **kwargs) as process: File "C:\Users\users\AppData\Local\Programs\Python\Python37\lib\subprocess.py", line 800, in **init** restore_signals, start_new_session) File "C:\Users\users\AppData\Local\Programs\Python\Python37\lib\subprocess.py", line 1207, in _execute_child startupinfo) FileNotFoundError: [WinError 2] The system cannot find the file specified
> 
> any ideas on how to fix?

It is because Windows blocks access to hidden files/paths while executing this script, You would need to have some experience on OpenCV & Python inorder to rewrite some of the code to be compatible with Windows, Your best bet is to install Ubuntu along side Windows then refollow the steps to get this working!

**Comment by CrystalOrder** [comment]
Ah shoot, I'm not the strongest coder. Thanks for letting me know what the issue is

**Comment by zoeywowy** [comment]
> Ah shoot, I'm not the strongest coder. Thanks for letting me know what the issue is

Glad to help heres a [video on setting-up Ubuntu alongside Windows](https://youtu.be/mXyN1aJYefc?si=8tMmnJz_35RQV1gv) this was my only option since like you idk how to code either best of luck! ^^
