### ISSUE TITLE
Error when running adb_autoplay.py

### ISSUE THREAD

**Issue by taylormacdonald-git** [shikhar1verma/auto-eatventure#4]
java.lang.NullPointerException: Cannot invoke "com.jetbrains.python.run.PyCommonOptionsFormFactory.createForm(com.jetbrains.python.run.PyCommonOptionsFormData)" because the return value of "com.jetbrains.python.run.PyCommonOptionsFormFactory.getInstance()" is null
	at com.jetbrains.python.run.PythonRunConfigurationForm.<init>(PythonRunConfigurationForm.java:74)
	at com.jetbrains.python.run.PythonRunConfigurationEditor.<init>(PythonRunConfigurationEditor.java:17)
	at com.jetbrains.python.run.PythonRunConfiguration.createConfigurationEditor(PythonRunConfiguration.java:57)
	at com.jetbrains.python.run.AbstractPythonRunConfiguration.getConfigurationEditor(AbstractPythonRunConfiguration.java:121)
	at com.intellij.execution.impl.ConfigurationSettingsEditorWrapper.createWrapper(ConfigurationSettingsEditorWrapper.java:225)
	at com.intellij.execution.impl.SingleConfigurationConfigurable.<init>(SingleConfigurationConfigurable.java:77)
	at com.intellij.execution.impl.SingleConfigurationConfigurable.editSettings(SingleConfigurationConfigurable.java:116)
	at com.intellij.execution.impl.RunDialog.editConfiguration(RunDialog.java:107)
	at com.intellij.execution.impl.RunDialog.editConfiguration(RunDialog.java:100)
	at com.intellij.execution.impl.ExecutionManagerImpl$executeConfiguration$2.accept(ExecutionManagerImpl.kt:681)
	at com.intellij.execution.impl.ExecutionManagerImpl$executeConfiguration$2.accept(ExecutionManagerImpl.kt:72)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.lambda$safeTransferToEdt$6(NonBlockingReadActionImpl.java:596)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:209)
	at com.intellij.openapi.application.TransactionGuardImpl.access$100(TransactionGuardImpl.java:21)
	at com.intellij.openapi.application.TransactionGuardImpl$1.run(TransactionGuardImpl.java:191)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:881)
	at com.intellij.openapi.application.impl.ApplicationImpl$3.run(ApplicationImpl.java:513)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:75)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:118)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:42)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:786)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:737)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:731)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:756)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:918)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:766)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:450)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:791)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:449)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:105)
	at com.intellij.ide.IdeEventQueue.performActivity(IdeEventQueue.java:624)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:447)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:881)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:493)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)

**Comment by shikhar1verma** [comment]
Seems like you are running a python script through Java. But I'll surely go through the error in depth later in the day.

**Comment by zoeywowy** [comment]
I know a way of setting this up if your on windows or mac!

1. Watch one of these videos on how to setup a dual boot os with Ubuntu [**_Watch this If your running Windows OS_**](https://youtu.be/mXyN1aJYefc?si=DXozbTno9lF2u0OU) | [**_Watch this if your running macOS_**](https://youtu.be/KIgxEEzT9ek?si=7Pymn1ybhzGDFSyd)
2. Once installed open the terminal(crtl+alt+T)
3. Now input these commands one after the other to install Python -- `sudo apt update`
`sudo apt install build-essential zlib1g-dev libncurses5-dev libgdbm-dev libnss3-dev libssl-dev libreadline-dev libffi-dev wget`
`sudo mkdir /python && cd /python`
`sudo wget https://www.python.org/ftp/python/3.7.6/Python-3.7.6.tgz`
`sudo tar -xvf Python-3.7.6.tgz`
`cd Python-3.7.6`
`sudo ./configure --enable-optimizations`
`sudo make install`
`python3.7 --version`
4. After that in a new terminal(ctrl+alt+T) input these to install Android Studio -- `sudo apt install openjdk-11-jdk
java --version`
`sudo add-apt-repository ppa:maarten-fonville/android-studio`
`sudo apt update`
`sudo apt install android-studio -y`
5. [**_Now watch this video on how to setup the emulator_**](https://youtu.be/GhuiNcOEv1A?t=91)
6. Next install the ADB files from the terminal you have opened via this command `sudo apt-get install android-sdk-platform-tools`
7. Now input in the same terminal this to install git for cloning the github repository `sudo apt-get install git-all`
8. Download Visual Studio Code from the app center once downloaded click on view then Command Pallet then type in git then click on git clone then paste in this link and hit enter `git clone https://github.com/shikhar1verma/auto-eatventure.git`
9. Then input this into terminal to make the directory for the ENV `sudo mkdir /python-environments && cd /python-environments`
10. Then input in terminal `python3.7 -m venv eatventures-env`
11. Now input in terminal to activate the ENV `source ~/python-environments/eatventures-env/bin/activate`
12. Next in the same terminal input `cd /[the location where repository is]/[next location maybe your name]/auto-eatventure`
13. When the terminal is in the repository directory input this `pip install -r requirements.txt`
14. If you get an Pillow error input this `sudo apt install zlib1g-dev libjpeg-dev` then input `pip install -r requirements.txt` again to finish install
15. Finally but not least [**_download the latest version of Eatventure_**](https://www.google.com/amp/s/apkpure.com/eatventure/com.hwqgrhhjfd.idlefastfood/amp)
16. Open up the emulator you made earlier then drag and drop the apk then let it install once downloaded open it up then login
17. Finally input this to start the automation process `python3.7 adb_autoplay.py`
18. Additionally but highly recommended install MaxAutoClicker from the app center as the bot gets stuck on some gui so once you download it put it on a timer for 15 seconds then click emulate human clicking then set its clicking position on the grass tile or something thats not really in the way and don't worry about the ads since they don't have redirect links hope this helps and enjoy! <3
